---
apiVersion: v1
kind: Service
metadata:
  name: skillhub-service
  labels:
    app: skillhub
spec:
  type: NodePort
  selector:
    app: skillhub  # Must match the label in the Deployment's pod template
  ports:
    - protocol: TCP
      port: 3000       # The port exposed by the Service
      targetPort: 3000 # The port your container listens on
      nodePort: 31000  # Optional, specify a custom NodePort in the 30000-32767 range

