---
apiVersion: v1
kind: Service
metadata:
  name: skillhub-service
  labels:
    app: skillhub
spec:
  type: NodePort
  selector:
    app: skillhub  
  ports:
    - protocol: TCP
      port: 3000      
      targetPort: 5173 
      nodePort: 31000 

