version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb+srv://TalhaSyed:Talha12@cluster0.4sldu.mongodb.net/Skillhub?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend:/usr/src/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/src/app
    restart: always
