version: '3.8'

services:
  backend:
    image: talhahussainx673/skillhub-backend:latest
    container_name: skillhub-backend
    ports:
      - "4000:4000" 
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - .env
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: skillhub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:
